name = "examensradar"
main = ".output/server/index.mjs"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NTFY_BASE_URL = "https://ntfy.sh"

[[d1_databases]]
binding = "DB"
database_name = "examensradar-db"
database_id = "f8fb4359-4690-4244-9d4e-34ad69bbeb4f"
migrations_dir = "drizzle/migrations"
